"""initial migration

Revision ID: c42133a612be
Revises: 
Create Date: 2025-04-08 13:49:36.004225

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'c42133a612be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign key constraints first
    op.execute('ALTER TABLE AspNetUserClaims DROP CONSTRAINT FK_AspNetUserClaims_AspNetUsers_UserId')
    op.execute('ALTER TABLE AspNetUserLogins DROP CONSTRAINT FK_AspNetUserLogins_AspNetUsers_UserId')
    op.execute('ALTER TABLE AspNetUserRoles DROP CONSTRAINT FK_AspNetUserRoles_AspNetUsers_UserId')
    op.execute('ALTER TABLE AspNetUserRoles DROP CONSTRAINT FK_AspNetUserRoles_AspNetRoles_RoleId')
    op.execute('ALTER TABLE AspNetRoleClaims DROP CONSTRAINT FK_AspNetRoleClaims_AspNetRoles_RoleId')
    op.execute('ALTER TABLE AspNetUserTokens DROP CONSTRAINT FK_AspNetUserTokens_AspNetUsers_UserId')
    op.execute('ALTER TABLE SubCategories DROP CONSTRAINT FK_SubCategories_Categories_CategoryId')

    # Drop tables in correct order
    op.drop_table('AspNetUserClaims')
    op.drop_table('AspNetUserLogins')
    op.drop_table('AspNetUserRoles')
    op.drop_table('AspNetRoleClaims')
    op.drop_table('AspNetUserTokens')
    op.drop_table('AspNetUsers')
    op.drop_table('AspNetRoles')
    op.drop_table('__EFMigrationsHistory')
    op.drop_table('TenantInfos')
    op.drop_table('SubCategories')
    op.drop_table('Categories')

    # Create new tables
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=64), nullable=False),
        sa.Column('email', sa.String(length=120), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
