"""add schema storage table

Revision ID: d42133a612be
Revises: c42133a612be
Create Date: 2025-04-08 18:24:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'd42133a612be'
down_revision = 'c42133a612be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schema_storage',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('table_name', sa.String(length=128), nullable=False),
        sa.Column('schema_metadata', sa.JSON(), nullable=True),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('embedding', sa.LargeBinary(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('table_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schema_storage')
    # ### end Alembic commands ###
